#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinix
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="testing")]
	public partial class TESTINGDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBacSi(BacSi instance);
    partial void UpdateBacSi(BacSi instance);
    partial void DeleteBacSi(BacSi instance);
    partial void InsertBaoCao(BaoCao instance);
    partial void UpdateBaoCao(BaoCao instance);
    partial void DeleteBaoCao(BaoCao instance);
    partial void InsertBenhNhan(BenhNhan instance);
    partial void UpdateBenhNhan(BenhNhan instance);
    partial void DeleteBenhNhan(BenhNhan instance);
    partial void InsertChiTietBaoCao(ChiTietBaoCao instance);
    partial void UpdateChiTietBaoCao(ChiTietBaoCao instance);
    partial void DeleteChiTietBaoCao(ChiTietBaoCao instance);
    partial void InsertChiTietDonThuoc(ChiTietDonThuoc instance);
    partial void UpdateChiTietDonThuoc(ChiTietDonThuoc instance);
    partial void DeleteChiTietDonThuoc(ChiTietDonThuoc instance);
    partial void InsertDichVu(DichVu instance);
    partial void UpdateDichVu(DichVu instance);
    partial void DeleteDichVu(DichVu instance);
    partial void InsertDonThuoc(DonThuoc instance);
    partial void UpdateDonThuoc(DonThuoc instance);
    partial void DeleteDonThuoc(DonThuoc instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertLeTan(LeTan instance);
    partial void UpdateLeTan(LeTan instance);
    partial void DeleteLeTan(LeTan instance);
    partial void InsertLichHen(LichHen instance);
    partial void UpdateLichHen(LichHen instance);
    partial void DeleteLichHen(LichHen instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertPhieuChiDinh(PhieuChiDinh instance);
    partial void UpdatePhieuChiDinh(PhieuChiDinh instance);
    partial void DeletePhieuChiDinh(PhieuChiDinh instance);
    partial void InsertPhieuKham(PhieuKham instance);
    partial void UpdatePhieuKham(PhieuKham instance);
    partial void DeletePhieuKham(PhieuKham instance);
    partial void InsertQuanLy(QuanLy instance);
    partial void UpdateQuanLy(QuanLy instance);
    partial void DeleteQuanLy(QuanLy instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertThuoc(Thuoc instance);
    partial void UpdateThuoc(Thuoc instance);
    partial void DeleteThuoc(Thuoc instance);
    #endregion
		
		public TESTINGDataContext() : 
				base(global::QLPhongKham.Properties.Settings.Default.testingConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TESTINGDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TESTINGDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TESTINGDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TESTINGDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BacSi> BacSis
		{
			get
			{
				return this.GetTable<BacSi>();
			}
		}
		
		public System.Data.Linq.Table<BaoCao> BaoCaos
		{
			get
			{
				return this.GetTable<BaoCao>();
			}
		}
		
		public System.Data.Linq.Table<BenhNhan> BenhNhans
		{
			get
			{
				return this.GetTable<BenhNhan>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietBaoCao> ChiTietBaoCaos
		{
			get
			{
				return this.GetTable<ChiTietBaoCao>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietDonThuoc> ChiTietDonThuocs
		{
			get
			{
				return this.GetTable<ChiTietDonThuoc>();
			}
		}
		
		public System.Data.Linq.Table<DichVu> DichVus
		{
			get
			{
				return this.GetTable<DichVu>();
			}
		}
		
		public System.Data.Linq.Table<DonThuoc> DonThuocs
		{
			get
			{
				return this.GetTable<DonThuoc>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<LeTan> LeTans
		{
			get
			{
				return this.GetTable<LeTan>();
			}
		}
		
		public System.Data.Linq.Table<LichHen> LichHens
		{
			get
			{
				return this.GetTable<LichHen>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<PhieuChiDinh> PhieuChiDinhs
		{
			get
			{
				return this.GetTable<PhieuChiDinh>();
			}
		}
		
		public System.Data.Linq.Table<PhieuKham> PhieuKhams
		{
			get
			{
				return this.GetTable<PhieuKham>();
			}
		}
		
		public System.Data.Linq.Table<QuanLy> QuanLies
		{
			get
			{
				return this.GetTable<QuanLy>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<Thuoc> Thuocs
		{
			get
			{
				return this.GetTable<Thuoc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BacSi")]
	public partial class BacSi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBacSi;
		
		private string _ChuyenMon;
		
		private string _MaNguoiDung;
		
		private EntitySet<PhieuKham> _PhieuKhams;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBacSiChanging(string value);
    partial void OnMaBacSiChanged();
    partial void OnChuyenMonChanging(string value);
    partial void OnChuyenMonChanged();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    #endregion
		
		public BacSi()
		{
			this._PhieuKhams = new EntitySet<PhieuKham>(new Action<PhieuKham>(this.attach_PhieuKhams), new Action<PhieuKham>(this.detach_PhieuKhams));
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBacSi", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBacSi
		{
			get
			{
				return this._MaBacSi;
			}
			set
			{
				if ((this._MaBacSi != value))
				{
					this.OnMaBacSiChanging(value);
					this.SendPropertyChanging();
					this._MaBacSi = value;
					this.SendPropertyChanged("MaBacSi");
					this.OnMaBacSiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenMon", DbType="NVarChar(255)")]
		public string ChuyenMon
		{
			get
			{
				return this._ChuyenMon;
			}
			set
			{
				if ((this._ChuyenMon != value))
				{
					this.OnChuyenMonChanging(value);
					this.SendPropertyChanging();
					this._ChuyenMon = value;
					this.SendPropertyChanged("ChuyenMon");
					this.OnChuyenMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="VarChar(10)")]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BacSi_PhieuKham", Storage="_PhieuKhams", ThisKey="MaBacSi", OtherKey="MaBacSi")]
		public EntitySet<PhieuKham> PhieuKhams
		{
			get
			{
				return this._PhieuKhams;
			}
			set
			{
				this._PhieuKhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_BacSi", Storage="_NguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.BacSis.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.BacSis.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuKhams(PhieuKham entity)
		{
			this.SendPropertyChanging();
			entity.BacSi = this;
		}
		
		private void detach_PhieuKhams(PhieuKham entity)
		{
			this.SendPropertyChanging();
			entity.BacSi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BaoCao")]
	public partial class BaoCao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBaoCao;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private string _LoaiBaoCao;
		
		private string _MaQuanLy;
		
		private EntitySet<ChiTietBaoCao> _ChiTietBaoCaos;
		
		private EntityRef<QuanLy> _QuanLy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBaoCaoChanging(string value);
    partial void OnMaBaoCaoChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnLoaiBaoCaoChanging(string value);
    partial void OnLoaiBaoCaoChanged();
    partial void OnMaQuanLyChanging(string value);
    partial void OnMaQuanLyChanged();
    #endregion
		
		public BaoCao()
		{
			this._ChiTietBaoCaos = new EntitySet<ChiTietBaoCao>(new Action<ChiTietBaoCao>(this.attach_ChiTietBaoCaos), new Action<ChiTietBaoCao>(this.detach_ChiTietBaoCaos));
			this._QuanLy = default(EntityRef<QuanLy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaoCao", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBaoCao
		{
			get
			{
				return this._MaBaoCao;
			}
			set
			{
				if ((this._MaBaoCao != value))
				{
					this.OnMaBaoCaoChanging(value);
					this.SendPropertyChanging();
					this._MaBaoCao = value;
					this.SendPropertyChanged("MaBaoCao");
					this.OnMaBaoCaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiBaoCao", DbType="NVarChar(255)")]
		public string LoaiBaoCao
		{
			get
			{
				return this._LoaiBaoCao;
			}
			set
			{
				if ((this._LoaiBaoCao != value))
				{
					this.OnLoaiBaoCaoChanging(value);
					this.SendPropertyChanging();
					this._LoaiBaoCao = value;
					this.SendPropertyChanged("LoaiBaoCao");
					this.OnLoaiBaoCaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuanLy", DbType="VarChar(10)")]
		public string MaQuanLy
		{
			get
			{
				return this._MaQuanLy;
			}
			set
			{
				if ((this._MaQuanLy != value))
				{
					if (this._QuanLy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQuanLyChanging(value);
					this.SendPropertyChanging();
					this._MaQuanLy = value;
					this.SendPropertyChanged("MaQuanLy");
					this.OnMaQuanLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BaoCao_ChiTietBaoCao", Storage="_ChiTietBaoCaos", ThisKey="MaBaoCao", OtherKey="MaBaoCao")]
		public EntitySet<ChiTietBaoCao> ChiTietBaoCaos
		{
			get
			{
				return this._ChiTietBaoCaos;
			}
			set
			{
				this._ChiTietBaoCaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanLy_BaoCao", Storage="_QuanLy", ThisKey="MaQuanLy", OtherKey="MaQuanLy", IsForeignKey=true)]
		public QuanLy QuanLy
		{
			get
			{
				return this._QuanLy.Entity;
			}
			set
			{
				QuanLy previousValue = this._QuanLy.Entity;
				if (((previousValue != value) 
							|| (this._QuanLy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuanLy.Entity = null;
						previousValue.BaoCaos.Remove(this);
					}
					this._QuanLy.Entity = value;
					if ((value != null))
					{
						value.BaoCaos.Add(this);
						this._MaQuanLy = value.MaQuanLy;
					}
					else
					{
						this._MaQuanLy = default(string);
					}
					this.SendPropertyChanged("QuanLy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietBaoCaos(ChiTietBaoCao entity)
		{
			this.SendPropertyChanging();
			entity.BaoCao = this;
		}
		
		private void detach_ChiTietBaoCaos(ChiTietBaoCao entity)
		{
			this.SendPropertyChanging();
			entity.BaoCao = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BenhNhan")]
	public partial class BenhNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBenhNhan;
		
		private string _TenBenhNhan;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private EntitySet<LichHen> _LichHens;
		
		private EntitySet<PhieuKham> _PhieuKhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBenhNhanChanging(string value);
    partial void OnMaBenhNhanChanged();
    partial void OnTenBenhNhanChanging(string value);
    partial void OnTenBenhNhanChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public BenhNhan()
		{
			this._LichHens = new EntitySet<LichHen>(new Action<LichHen>(this.attach_LichHens), new Action<LichHen>(this.detach_LichHens));
			this._PhieuKhams = new EntitySet<PhieuKham>(new Action<PhieuKham>(this.attach_PhieuKhams), new Action<PhieuKham>(this.detach_PhieuKhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBenhNhan", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBenhNhan
		{
			get
			{
				return this._MaBenhNhan;
			}
			set
			{
				if ((this._MaBenhNhan != value))
				{
					this.OnMaBenhNhanChanging(value);
					this.SendPropertyChanging();
					this._MaBenhNhan = value;
					this.SendPropertyChanged("MaBenhNhan");
					this.OnMaBenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBenhNhan", DbType="NVarChar(255)")]
		public string TenBenhNhan
		{
			get
			{
				return this._TenBenhNhan;
			}
			set
			{
				if ((this._TenBenhNhan != value))
				{
					this.OnTenBenhNhanChanging(value);
					this.SendPropertyChanging();
					this._TenBenhNhan = value;
					this.SendPropertyChanged("TenBenhNhan");
					this.OnTenBenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_LichHen", Storage="_LichHens", ThisKey="MaBenhNhan", OtherKey="MaBenhNhan")]
		public EntitySet<LichHen> LichHens
		{
			get
			{
				return this._LichHens;
			}
			set
			{
				this._LichHens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_PhieuKham", Storage="_PhieuKhams", ThisKey="MaBenhNhan", OtherKey="MaBenhNhan")]
		public EntitySet<PhieuKham> PhieuKhams
		{
			get
			{
				return this._PhieuKhams;
			}
			set
			{
				this._PhieuKhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichHens(LichHen entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = this;
		}
		
		private void detach_LichHens(LichHen entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = null;
		}
		
		private void attach_PhieuKhams(PhieuKham entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = this;
		}
		
		private void detach_PhieuKhams(PhieuKham entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietBaoCao")]
	public partial class ChiTietBaoCao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBaoCao;
		
		private string _MaHoaDon;
		
		private EntityRef<BaoCao> _BaoCao;
		
		private EntityRef<HoaDon> _HoaDon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBaoCaoChanging(string value);
    partial void OnMaBaoCaoChanged();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    #endregion
		
		public ChiTietBaoCao()
		{
			this._BaoCao = default(EntityRef<BaoCao>);
			this._HoaDon = default(EntityRef<HoaDon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaoCao", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBaoCao
		{
			get
			{
				return this._MaBaoCao;
			}
			set
			{
				if ((this._MaBaoCao != value))
				{
					if (this._BaoCao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBaoCaoChanging(value);
					this.SendPropertyChanging();
					this._MaBaoCao = value;
					this.SendPropertyChanged("MaBaoCao");
					this.OnMaBaoCaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BaoCao_ChiTietBaoCao", Storage="_BaoCao", ThisKey="MaBaoCao", OtherKey="MaBaoCao", IsForeignKey=true)]
		public BaoCao BaoCao
		{
			get
			{
				return this._BaoCao.Entity;
			}
			set
			{
				BaoCao previousValue = this._BaoCao.Entity;
				if (((previousValue != value) 
							|| (this._BaoCao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BaoCao.Entity = null;
						previousValue.ChiTietBaoCaos.Remove(this);
					}
					this._BaoCao.Entity = value;
					if ((value != null))
					{
						value.ChiTietBaoCaos.Add(this);
						this._MaBaoCao = value.MaBaoCao;
					}
					else
					{
						this._MaBaoCao = default(string);
					}
					this.SendPropertyChanged("BaoCao");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietBaoCao", Storage="_HoaDon", ThisKey="MaHoaDon", OtherKey="MaHoaDon", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.ChiTietBaoCaos.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.ChiTietBaoCaos.Add(this);
						this._MaHoaDon = value.MaHoaDon;
					}
					else
					{
						this._MaHoaDon = default(string);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDonThuoc")]
	public partial class ChiTietDonThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDonThuoc;
		
		private string _MaThuoc;
		
		private string _LieuLuong;
		
		private System.Nullable<int> _SoLuong;
		
		private EntityRef<DonThuoc> _DonThuoc;
		
		private EntityRef<Thuoc> _Thuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonThuocChanging(string value);
    partial void OnMaDonThuocChanged();
    partial void OnMaThuocChanging(string value);
    partial void OnMaThuocChanged();
    partial void OnLieuLuongChanging(string value);
    partial void OnLieuLuongChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public ChiTietDonThuoc()
		{
			this._DonThuoc = default(EntityRef<DonThuoc>);
			this._Thuoc = default(EntityRef<Thuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonThuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDonThuoc
		{
			get
			{
				return this._MaDonThuoc;
			}
			set
			{
				if ((this._MaDonThuoc != value))
				{
					if (this._DonThuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonThuocChanging(value);
					this.SendPropertyChanging();
					this._MaDonThuoc = value;
					this.SendPropertyChanged("MaDonThuoc");
					this.OnMaDonThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThuoc
		{
			get
			{
				return this._MaThuoc;
			}
			set
			{
				if ((this._MaThuoc != value))
				{
					if (this._Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThuocChanging(value);
					this.SendPropertyChanging();
					this._MaThuoc = value;
					this.SendPropertyChanged("MaThuoc");
					this.OnMaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LieuLuong", DbType="NVarChar(50)")]
		public string LieuLuong
		{
			get
			{
				return this._LieuLuong;
			}
			set
			{
				if ((this._LieuLuong != value))
				{
					this.OnLieuLuongChanging(value);
					this.SendPropertyChanging();
					this._LieuLuong = value;
					this.SendPropertyChanged("LieuLuong");
					this.OnLieuLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonThuoc_ChiTietDonThuoc", Storage="_DonThuoc", ThisKey="MaDonThuoc", OtherKey="MaDonThuoc", IsForeignKey=true)]
		public DonThuoc DonThuoc
		{
			get
			{
				return this._DonThuoc.Entity;
			}
			set
			{
				DonThuoc previousValue = this._DonThuoc.Entity;
				if (((previousValue != value) 
							|| (this._DonThuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonThuoc.Entity = null;
						previousValue.ChiTietDonThuocs.Remove(this);
					}
					this._DonThuoc.Entity = value;
					if ((value != null))
					{
						value.ChiTietDonThuocs.Add(this);
						this._MaDonThuoc = value.MaDonThuoc;
					}
					else
					{
						this._MaDonThuoc = default(string);
					}
					this.SendPropertyChanged("DonThuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_ChiTietDonThuoc", Storage="_Thuoc", ThisKey="MaThuoc", OtherKey="MaThuoc", IsForeignKey=true)]
		public Thuoc Thuoc
		{
			get
			{
				return this._Thuoc.Entity;
			}
			set
			{
				Thuoc previousValue = this._Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuoc.Entity = null;
						previousValue.ChiTietDonThuocs.Remove(this);
					}
					this._Thuoc.Entity = value;
					if ((value != null))
					{
						value.ChiTietDonThuocs.Add(this);
						this._MaThuoc = value.MaThuoc;
					}
					else
					{
						this._MaThuoc = default(string);
					}
					this.SendPropertyChanged("Thuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVu")]
	public partial class DichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDichVu;
		
		private string _TenDichVu;
		
		private System.Nullable<decimal> _DonGia;
		
		private EntitySet<PhieuChiDinh> _PhieuChiDinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDichVuChanging(string value);
    partial void OnMaDichVuChanged();
    partial void OnTenDichVuChanging(string value);
    partial void OnTenDichVuChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public DichVu()
		{
			this._PhieuChiDinhs = new EntitySet<PhieuChiDinh>(new Action<PhieuChiDinh>(this.attach_PhieuChiDinhs), new Action<PhieuChiDinh>(this.detach_PhieuChiDinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDichVu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDichVu
		{
			get
			{
				return this._MaDichVu;
			}
			set
			{
				if ((this._MaDichVu != value))
				{
					this.OnMaDichVuChanging(value);
					this.SendPropertyChanging();
					this._MaDichVu = value;
					this.SendPropertyChanged("MaDichVu");
					this.OnMaDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDichVu", DbType="NVarChar(255)")]
		public string TenDichVu
		{
			get
			{
				return this._TenDichVu;
			}
			set
			{
				if ((this._TenDichVu != value))
				{
					this.OnTenDichVuChanging(value);
					this.SendPropertyChanging();
					this._TenDichVu = value;
					this.SendPropertyChanged("TenDichVu");
					this.OnTenDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_PhieuChiDinh", Storage="_PhieuChiDinhs", ThisKey="MaDichVu", OtherKey="MaDichVu")]
		public EntitySet<PhieuChiDinh> PhieuChiDinhs
		{
			get
			{
				return this._PhieuChiDinhs;
			}
			set
			{
				this._PhieuChiDinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuChiDinhs(PhieuChiDinh entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = this;
		}
		
		private void detach_PhieuChiDinhs(PhieuChiDinh entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonThuoc")]
	public partial class DonThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDonThuoc;
		
		private System.Nullable<System.DateTime> _NgayKeDon;
		
		private string _GhiChu;
		
		private string _MaPhieuKham;
		
		private EntitySet<ChiTietDonThuoc> _ChiTietDonThuocs;
		
		private EntityRef<PhieuKham> _PhieuKham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonThuocChanging(string value);
    partial void OnMaDonThuocChanged();
    partial void OnNgayKeDonChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKeDonChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnMaPhieuKhamChanging(string value);
    partial void OnMaPhieuKhamChanged();
    #endregion
		
		public DonThuoc()
		{
			this._ChiTietDonThuocs = new EntitySet<ChiTietDonThuoc>(new Action<ChiTietDonThuoc>(this.attach_ChiTietDonThuocs), new Action<ChiTietDonThuoc>(this.detach_ChiTietDonThuocs));
			this._PhieuKham = default(EntityRef<PhieuKham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonThuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDonThuoc
		{
			get
			{
				return this._MaDonThuoc;
			}
			set
			{
				if ((this._MaDonThuoc != value))
				{
					this.OnMaDonThuocChanging(value);
					this.SendPropertyChanging();
					this._MaDonThuoc = value;
					this.SendPropertyChanged("MaDonThuoc");
					this.OnMaDonThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKeDon", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKeDon
		{
			get
			{
				return this._NgayKeDon;
			}
			set
			{
				if ((this._NgayKeDon != value))
				{
					this.OnNgayKeDonChanging(value);
					this.SendPropertyChanging();
					this._NgayKeDon = value;
					this.SendPropertyChanged("NgayKeDon");
					this.OnNgayKeDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuKham", DbType="VarChar(10)")]
		public string MaPhieuKham
		{
			get
			{
				return this._MaPhieuKham;
			}
			set
			{
				if ((this._MaPhieuKham != value))
				{
					if (this._PhieuKham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuKhamChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuKham = value;
					this.SendPropertyChanged("MaPhieuKham");
					this.OnMaPhieuKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonThuoc_ChiTietDonThuoc", Storage="_ChiTietDonThuocs", ThisKey="MaDonThuoc", OtherKey="MaDonThuoc")]
		public EntitySet<ChiTietDonThuoc> ChiTietDonThuocs
		{
			get
			{
				return this._ChiTietDonThuocs;
			}
			set
			{
				this._ChiTietDonThuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuKham_DonThuoc", Storage="_PhieuKham", ThisKey="MaPhieuKham", OtherKey="MaPhieuKham", IsForeignKey=true)]
		public PhieuKham PhieuKham
		{
			get
			{
				return this._PhieuKham.Entity;
			}
			set
			{
				PhieuKham previousValue = this._PhieuKham.Entity;
				if (((previousValue != value) 
							|| (this._PhieuKham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuKham.Entity = null;
						previousValue.DonThuocs.Remove(this);
					}
					this._PhieuKham.Entity = value;
					if ((value != null))
					{
						value.DonThuocs.Add(this);
						this._MaPhieuKham = value.MaPhieuKham;
					}
					else
					{
						this._MaPhieuKham = default(string);
					}
					this.SendPropertyChanged("PhieuKham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDonThuocs(ChiTietDonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.DonThuoc = this;
		}
		
		private void detach_ChiTietDonThuocs(ChiTietDonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.DonThuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private System.Nullable<decimal> _SoTien;
		
		private string _PhuongThucTT;
		
		private string _TrangThai;
		
		private System.Nullable<System.DateTime> _ThoiGianTT;
		
		private string _GhiChu;
		
		private string _MaLeTan;
		
		private string _MaPhieuKham;
		
		private EntitySet<ChiTietBaoCao> _ChiTietBaoCaos;
		
		private EntityRef<LeTan> _LeTan;
		
		private EntityRef<PhieuKham> _PhieuKham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnSoTienChanging(System.Nullable<decimal> value);
    partial void OnSoTienChanged();
    partial void OnPhuongThucTTChanging(string value);
    partial void OnPhuongThucTTChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnThoiGianTTChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianTTChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnMaLeTanChanging(string value);
    partial void OnMaLeTanChanged();
    partial void OnMaPhieuKhamChanging(string value);
    partial void OnMaPhieuKhamChanged();
    #endregion
		
		public HoaDon()
		{
			this._ChiTietBaoCaos = new EntitySet<ChiTietBaoCao>(new Action<ChiTietBaoCao>(this.attach_ChiTietBaoCaos), new Action<ChiTietBaoCao>(this.detach_ChiTietBaoCaos));
			this._LeTan = default(EntityRef<LeTan>);
			this._PhieuKham = default(EntityRef<PhieuKham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongThucTT", DbType="NVarChar(50)")]
		public string PhuongThucTT
		{
			get
			{
				return this._PhuongThucTT;
			}
			set
			{
				if ((this._PhuongThucTT != value))
				{
					this.OnPhuongThucTTChanging(value);
					this.SendPropertyChanging();
					this._PhuongThucTT = value;
					this.SendPropertyChanged("PhuongThucTT");
					this.OnPhuongThucTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianTT", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianTT
		{
			get
			{
				return this._ThoiGianTT;
			}
			set
			{
				if ((this._ThoiGianTT != value))
				{
					this.OnThoiGianTTChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianTT = value;
					this.SendPropertyChanged("ThoiGianTT");
					this.OnThoiGianTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLeTan", DbType="VarChar(10)")]
		public string MaLeTan
		{
			get
			{
				return this._MaLeTan;
			}
			set
			{
				if ((this._MaLeTan != value))
				{
					if (this._LeTan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLeTanChanging(value);
					this.SendPropertyChanging();
					this._MaLeTan = value;
					this.SendPropertyChanged("MaLeTan");
					this.OnMaLeTanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuKham", DbType="VarChar(10)")]
		public string MaPhieuKham
		{
			get
			{
				return this._MaPhieuKham;
			}
			set
			{
				if ((this._MaPhieuKham != value))
				{
					if (this._PhieuKham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuKhamChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuKham = value;
					this.SendPropertyChanged("MaPhieuKham");
					this.OnMaPhieuKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietBaoCao", Storage="_ChiTietBaoCaos", ThisKey="MaHoaDon", OtherKey="MaHoaDon")]
		public EntitySet<ChiTietBaoCao> ChiTietBaoCaos
		{
			get
			{
				return this._ChiTietBaoCaos;
			}
			set
			{
				this._ChiTietBaoCaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LeTan_HoaDon", Storage="_LeTan", ThisKey="MaLeTan", OtherKey="MaLeTan", IsForeignKey=true)]
		public LeTan LeTan
		{
			get
			{
				return this._LeTan.Entity;
			}
			set
			{
				LeTan previousValue = this._LeTan.Entity;
				if (((previousValue != value) 
							|| (this._LeTan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LeTan.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._LeTan.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaLeTan = value.MaLeTan;
					}
					else
					{
						this._MaLeTan = default(string);
					}
					this.SendPropertyChanged("LeTan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuKham_HoaDon", Storage="_PhieuKham", ThisKey="MaPhieuKham", OtherKey="MaPhieuKham", IsForeignKey=true)]
		public PhieuKham PhieuKham
		{
			get
			{
				return this._PhieuKham.Entity;
			}
			set
			{
				PhieuKham previousValue = this._PhieuKham.Entity;
				if (((previousValue != value) 
							|| (this._PhieuKham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuKham.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._PhieuKham.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaPhieuKham = value.MaPhieuKham;
					}
					else
					{
						this._MaPhieuKham = default(string);
					}
					this.SendPropertyChanged("PhieuKham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietBaoCaos(ChiTietBaoCao entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_ChiTietBaoCaos(ChiTietBaoCao entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LeTan")]
	public partial class LeTan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLeTan;
		
		private string _MaNguoiDung;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLeTanChanging(string value);
    partial void OnMaLeTanChanged();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    #endregion
		
		public LeTan()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLeTan", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLeTan
		{
			get
			{
				return this._MaLeTan;
			}
			set
			{
				if ((this._MaLeTan != value))
				{
					this.OnMaLeTanChanging(value);
					this.SendPropertyChanging();
					this._MaLeTan = value;
					this.SendPropertyChanged("MaLeTan");
					this.OnMaLeTanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="VarChar(10)")]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LeTan_HoaDon", Storage="_HoaDons", ThisKey="MaLeTan", OtherKey="MaLeTan")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_LeTan", Storage="_NguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.LeTans.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.LeTans.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.LeTan = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.LeTan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichHen")]
	public partial class LichHen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLichHen;
		
		private System.Nullable<System.DateTime> _NgayHen;
		
		private System.Nullable<System.TimeSpan> _KhungGio;
		
		private string _TrangThai;
		
		private string _MaBenhNhan;
		
		private EntityRef<BenhNhan> _BenhNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLichHenChanging(string value);
    partial void OnMaLichHenChanged();
    partial void OnNgayHenChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHenChanged();
    partial void OnKhungGioChanging(System.Nullable<System.TimeSpan> value);
    partial void OnKhungGioChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnMaBenhNhanChanging(string value);
    partial void OnMaBenhNhanChanged();
    #endregion
		
		public LichHen()
		{
			this._BenhNhan = default(EntityRef<BenhNhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLichHen", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLichHen
		{
			get
			{
				return this._MaLichHen;
			}
			set
			{
				if ((this._MaLichHen != value))
				{
					this.OnMaLichHenChanging(value);
					this.SendPropertyChanging();
					this._MaLichHen = value;
					this.SendPropertyChanged("MaLichHen");
					this.OnMaLichHenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHen", DbType="Date")]
		public System.Nullable<System.DateTime> NgayHen
		{
			get
			{
				return this._NgayHen;
			}
			set
			{
				if ((this._NgayHen != value))
				{
					this.OnNgayHenChanging(value);
					this.SendPropertyChanging();
					this._NgayHen = value;
					this.SendPropertyChanged("NgayHen");
					this.OnNgayHenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhungGio", DbType="Time")]
		public System.Nullable<System.TimeSpan> KhungGio
		{
			get
			{
				return this._KhungGio;
			}
			set
			{
				if ((this._KhungGio != value))
				{
					this.OnKhungGioChanging(value);
					this.SendPropertyChanging();
					this._KhungGio = value;
					this.SendPropertyChanged("KhungGio");
					this.OnKhungGioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBenhNhan", DbType="VarChar(10)")]
		public string MaBenhNhan
		{
			get
			{
				return this._MaBenhNhan;
			}
			set
			{
				if ((this._MaBenhNhan != value))
				{
					if (this._BenhNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBenhNhanChanging(value);
					this.SendPropertyChanging();
					this._MaBenhNhan = value;
					this.SendPropertyChanged("MaBenhNhan");
					this.OnMaBenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_LichHen", Storage="_BenhNhan", ThisKey="MaBenhNhan", OtherKey="MaBenhNhan", IsForeignKey=true)]
		public BenhNhan BenhNhan
		{
			get
			{
				return this._BenhNhan.Entity;
			}
			set
			{
				BenhNhan previousValue = this._BenhNhan.Entity;
				if (((previousValue != value) 
							|| (this._BenhNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BenhNhan.Entity = null;
						previousValue.LichHens.Remove(this);
					}
					this._BenhNhan.Entity = value;
					if ((value != null))
					{
						value.LichHens.Add(this);
						this._MaBenhNhan = value.MaBenhNhan;
					}
					else
					{
						this._MaBenhNhan = default(string);
					}
					this.SendPropertyChanged("BenhNhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguoiDung;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private string _LoaiNguoiDung;
		
		private EntitySet<BacSi> _BacSis;
		
		private EntitySet<LeTan> _LeTans;
		
		private EntitySet<QuanLy> _QuanLies;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnLoaiNguoiDungChanging(string value);
    partial void OnLoaiNguoiDungChanged();
    #endregion
		
		public NguoiDung()
		{
			this._BacSis = new EntitySet<BacSi>(new Action<BacSi>(this.attach_BacSis), new Action<BacSi>(this.detach_BacSis));
			this._LeTans = new EntitySet<LeTan>(new Action<LeTan>(this.attach_LeTans), new Action<LeTan>(this.detach_LeTans));
			this._QuanLies = new EntitySet<QuanLy>(new Action<QuanLy>(this.attach_QuanLies), new Action<QuanLy>(this.detach_QuanLies));
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(255)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiNguoiDung", DbType="NVarChar(50)")]
		public string LoaiNguoiDung
		{
			get
			{
				return this._LoaiNguoiDung;
			}
			set
			{
				if ((this._LoaiNguoiDung != value))
				{
					this.OnLoaiNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._LoaiNguoiDung = value;
					this.SendPropertyChanged("LoaiNguoiDung");
					this.OnLoaiNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_BacSi", Storage="_BacSis", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<BacSi> BacSis
		{
			get
			{
				return this._BacSis;
			}
			set
			{
				this._BacSis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_LeTan", Storage="_LeTans", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<LeTan> LeTans
		{
			get
			{
				return this._LeTans;
			}
			set
			{
				this._LeTans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_QuanLy", Storage="_QuanLies", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<QuanLy> QuanLies
		{
			get
			{
				return this._QuanLies;
			}
			set
			{
				this._QuanLies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_TaiKhoan", Storage="_TaiKhoans", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BacSis(BacSi entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_BacSis(BacSi entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_LeTans(LeTan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_LeTans(LeTan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_QuanLies(QuanLy entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_QuanLies(QuanLy entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuChiDinh")]
	public partial class PhieuChiDinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuKham;
		
		private string _MaDichVu;
		
		private EntityRef<DichVu> _DichVu;
		
		private EntityRef<PhieuKham> _PhieuKham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuKhamChanging(string value);
    partial void OnMaPhieuKhamChanged();
    partial void OnMaDichVuChanging(string value);
    partial void OnMaDichVuChanged();
    #endregion
		
		public PhieuChiDinh()
		{
			this._DichVu = default(EntityRef<DichVu>);
			this._PhieuKham = default(EntityRef<PhieuKham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuKham", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuKham
		{
			get
			{
				return this._MaPhieuKham;
			}
			set
			{
				if ((this._MaPhieuKham != value))
				{
					if (this._PhieuKham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuKhamChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuKham = value;
					this.SendPropertyChanged("MaPhieuKham");
					this.OnMaPhieuKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDichVu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDichVu
		{
			get
			{
				return this._MaDichVu;
			}
			set
			{
				if ((this._MaDichVu != value))
				{
					if (this._DichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDichVuChanging(value);
					this.SendPropertyChanging();
					this._MaDichVu = value;
					this.SendPropertyChanged("MaDichVu");
					this.OnMaDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_PhieuChiDinh", Storage="_DichVu", ThisKey="MaDichVu", OtherKey="MaDichVu", IsForeignKey=true)]
		public DichVu DichVu
		{
			get
			{
				return this._DichVu.Entity;
			}
			set
			{
				DichVu previousValue = this._DichVu.Entity;
				if (((previousValue != value) 
							|| (this._DichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DichVu.Entity = null;
						previousValue.PhieuChiDinhs.Remove(this);
					}
					this._DichVu.Entity = value;
					if ((value != null))
					{
						value.PhieuChiDinhs.Add(this);
						this._MaDichVu = value.MaDichVu;
					}
					else
					{
						this._MaDichVu = default(string);
					}
					this.SendPropertyChanged("DichVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuKham_PhieuChiDinh", Storage="_PhieuKham", ThisKey="MaPhieuKham", OtherKey="MaPhieuKham", IsForeignKey=true)]
		public PhieuKham PhieuKham
		{
			get
			{
				return this._PhieuKham.Entity;
			}
			set
			{
				PhieuKham previousValue = this._PhieuKham.Entity;
				if (((previousValue != value) 
							|| (this._PhieuKham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuKham.Entity = null;
						previousValue.PhieuChiDinhs.Remove(this);
					}
					this._PhieuKham.Entity = value;
					if ((value != null))
					{
						value.PhieuChiDinhs.Add(this);
						this._MaPhieuKham = value.MaPhieuKham;
					}
					else
					{
						this._MaPhieuKham = default(string);
					}
					this.SendPropertyChanged("PhieuKham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuKham")]
	public partial class PhieuKham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuKham;
		
		private string _ChanDoan;
		
		private System.Nullable<System.DateTime> _NgayKham;
		
		private string _MaBacSi;
		
		private string _MaBenhNhan;
		
		private EntitySet<DonThuoc> _DonThuocs;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<PhieuChiDinh> _PhieuChiDinhs;
		
		private EntityRef<BacSi> _BacSi;
		
		private EntityRef<BenhNhan> _BenhNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuKhamChanging(string value);
    partial void OnMaPhieuKhamChanged();
    partial void OnChanDoanChanging(string value);
    partial void OnChanDoanChanged();
    partial void OnNgayKhamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKhamChanged();
    partial void OnMaBacSiChanging(string value);
    partial void OnMaBacSiChanged();
    partial void OnMaBenhNhanChanging(string value);
    partial void OnMaBenhNhanChanged();
    #endregion
		
		public PhieuKham()
		{
			this._DonThuocs = new EntitySet<DonThuoc>(new Action<DonThuoc>(this.attach_DonThuocs), new Action<DonThuoc>(this.detach_DonThuocs));
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._PhieuChiDinhs = new EntitySet<PhieuChiDinh>(new Action<PhieuChiDinh>(this.attach_PhieuChiDinhs), new Action<PhieuChiDinh>(this.detach_PhieuChiDinhs));
			this._BacSi = default(EntityRef<BacSi>);
			this._BenhNhan = default(EntityRef<BenhNhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuKham", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuKham
		{
			get
			{
				return this._MaPhieuKham;
			}
			set
			{
				if ((this._MaPhieuKham != value))
				{
					this.OnMaPhieuKhamChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuKham = value;
					this.SendPropertyChanged("MaPhieuKham");
					this.OnMaPhieuKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChanDoan", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ChanDoan
		{
			get
			{
				return this._ChanDoan;
			}
			set
			{
				if ((this._ChanDoan != value))
				{
					this.OnChanDoanChanging(value);
					this.SendPropertyChanging();
					this._ChanDoan = value;
					this.SendPropertyChanged("ChanDoan");
					this.OnChanDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKham", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKham
		{
			get
			{
				return this._NgayKham;
			}
			set
			{
				if ((this._NgayKham != value))
				{
					this.OnNgayKhamChanging(value);
					this.SendPropertyChanging();
					this._NgayKham = value;
					this.SendPropertyChanged("NgayKham");
					this.OnNgayKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBacSi", DbType="VarChar(10)")]
		public string MaBacSi
		{
			get
			{
				return this._MaBacSi;
			}
			set
			{
				if ((this._MaBacSi != value))
				{
					if (this._BacSi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBacSiChanging(value);
					this.SendPropertyChanging();
					this._MaBacSi = value;
					this.SendPropertyChanged("MaBacSi");
					this.OnMaBacSiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBenhNhan", DbType="VarChar(10)")]
		public string MaBenhNhan
		{
			get
			{
				return this._MaBenhNhan;
			}
			set
			{
				if ((this._MaBenhNhan != value))
				{
					if (this._BenhNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBenhNhanChanging(value);
					this.SendPropertyChanging();
					this._MaBenhNhan = value;
					this.SendPropertyChanged("MaBenhNhan");
					this.OnMaBenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuKham_DonThuoc", Storage="_DonThuocs", ThisKey="MaPhieuKham", OtherKey="MaPhieuKham")]
		public EntitySet<DonThuoc> DonThuocs
		{
			get
			{
				return this._DonThuocs;
			}
			set
			{
				this._DonThuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuKham_HoaDon", Storage="_HoaDons", ThisKey="MaPhieuKham", OtherKey="MaPhieuKham")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuKham_PhieuChiDinh", Storage="_PhieuChiDinhs", ThisKey="MaPhieuKham", OtherKey="MaPhieuKham")]
		public EntitySet<PhieuChiDinh> PhieuChiDinhs
		{
			get
			{
				return this._PhieuChiDinhs;
			}
			set
			{
				this._PhieuChiDinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BacSi_PhieuKham", Storage="_BacSi", ThisKey="MaBacSi", OtherKey="MaBacSi", IsForeignKey=true)]
		public BacSi BacSi
		{
			get
			{
				return this._BacSi.Entity;
			}
			set
			{
				BacSi previousValue = this._BacSi.Entity;
				if (((previousValue != value) 
							|| (this._BacSi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BacSi.Entity = null;
						previousValue.PhieuKhams.Remove(this);
					}
					this._BacSi.Entity = value;
					if ((value != null))
					{
						value.PhieuKhams.Add(this);
						this._MaBacSi = value.MaBacSi;
					}
					else
					{
						this._MaBacSi = default(string);
					}
					this.SendPropertyChanged("BacSi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_PhieuKham", Storage="_BenhNhan", ThisKey="MaBenhNhan", OtherKey="MaBenhNhan", IsForeignKey=true)]
		public BenhNhan BenhNhan
		{
			get
			{
				return this._BenhNhan.Entity;
			}
			set
			{
				BenhNhan previousValue = this._BenhNhan.Entity;
				if (((previousValue != value) 
							|| (this._BenhNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BenhNhan.Entity = null;
						previousValue.PhieuKhams.Remove(this);
					}
					this._BenhNhan.Entity = value;
					if ((value != null))
					{
						value.PhieuKhams.Add(this);
						this._MaBenhNhan = value.MaBenhNhan;
					}
					else
					{
						this._MaBenhNhan = default(string);
					}
					this.SendPropertyChanged("BenhNhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonThuocs(DonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.PhieuKham = this;
		}
		
		private void detach_DonThuocs(DonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.PhieuKham = null;
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.PhieuKham = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.PhieuKham = null;
		}
		
		private void attach_PhieuChiDinhs(PhieuChiDinh entity)
		{
			this.SendPropertyChanging();
			entity.PhieuKham = this;
		}
		
		private void detach_PhieuChiDinhs(PhieuChiDinh entity)
		{
			this.SendPropertyChanging();
			entity.PhieuKham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanLy")]
	public partial class QuanLy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaQuanLy;
		
		private string _MaNguoiDung;
		
		private EntitySet<BaoCao> _BaoCaos;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQuanLyChanging(string value);
    partial void OnMaQuanLyChanged();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    #endregion
		
		public QuanLy()
		{
			this._BaoCaos = new EntitySet<BaoCao>(new Action<BaoCao>(this.attach_BaoCaos), new Action<BaoCao>(this.detach_BaoCaos));
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuanLy", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaQuanLy
		{
			get
			{
				return this._MaQuanLy;
			}
			set
			{
				if ((this._MaQuanLy != value))
				{
					this.OnMaQuanLyChanging(value);
					this.SendPropertyChanging();
					this._MaQuanLy = value;
					this.SendPropertyChanged("MaQuanLy");
					this.OnMaQuanLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="VarChar(10)")]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanLy_BaoCao", Storage="_BaoCaos", ThisKey="MaQuanLy", OtherKey="MaQuanLy")]
		public EntitySet<BaoCao> BaoCaos
		{
			get
			{
				return this._BaoCaos;
			}
			set
			{
				this._BaoCaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_QuanLy", Storage="_NguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.QuanLies.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.QuanLies.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BaoCaos(BaoCao entity)
		{
			this.SendPropertyChanging();
			entity.QuanLy = this;
		}
		
		private void detach_BaoCaos(BaoCao entity)
		{
			this.SendPropertyChanging();
			entity.QuanLy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTaiKhoan;
		
		private string _TenTaiKhoan;
		
		private string _MatKhau;
		
		private string _MaNguoiDung;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTaiKhoanChanging(string value);
    partial void OnMaTaiKhoanChanged();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiKhoan", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTaiKhoan
		{
			get
			{
				return this._MaTaiKhoan;
			}
			set
			{
				if ((this._MaTaiKhoan != value))
				{
					this.OnMaTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._MaTaiKhoan = value;
					this.SendPropertyChanged("MaTaiKhoan");
					this.OnMaTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NVarChar(255)")]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(255)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="VarChar(10)")]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_TaiKhoan", Storage="_NguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thuoc")]
	public partial class Thuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThuoc;
		
		private string _TenThuoc;
		
		private string _DVT;
		
		private string _MoTa;
		
		private EntitySet<ChiTietDonThuoc> _ChiTietDonThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThuocChanging(string value);
    partial void OnMaThuocChanged();
    partial void OnTenThuocChanging(string value);
    partial void OnTenThuocChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public Thuoc()
		{
			this._ChiTietDonThuocs = new EntitySet<ChiTietDonThuoc>(new Action<ChiTietDonThuoc>(this.attach_ChiTietDonThuocs), new Action<ChiTietDonThuoc>(this.detach_ChiTietDonThuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThuoc
		{
			get
			{
				return this._MaThuoc;
			}
			set
			{
				if ((this._MaThuoc != value))
				{
					this.OnMaThuocChanging(value);
					this.SendPropertyChanging();
					this._MaThuoc = value;
					this.SendPropertyChanged("MaThuoc");
					this.OnMaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThuoc", DbType="NVarChar(255)")]
		public string TenThuoc
		{
			get
			{
				return this._TenThuoc;
			}
			set
			{
				if ((this._TenThuoc != value))
				{
					this.OnTenThuocChanging(value);
					this.SendPropertyChanging();
					this._TenThuoc = value;
					this.SendPropertyChanged("TenThuoc");
					this.OnTenThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(50)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_ChiTietDonThuoc", Storage="_ChiTietDonThuocs", ThisKey="MaThuoc", OtherKey="MaThuoc")]
		public EntitySet<ChiTietDonThuoc> ChiTietDonThuocs
		{
			get
			{
				return this._ChiTietDonThuocs;
			}
			set
			{
				this._ChiTietDonThuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDonThuocs(ChiTietDonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = this;
		}
		
		private void detach_ChiTietDonThuocs(ChiTietDonThuoc entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = null;
		}
	}
}
#pragma warning restore 1591
