//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinix.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MSI;Initial Catalog=DERMA_CLINIC;Integrated Security=True;TrustServer" +
            "Certificate=True")]
        public string DERMA_CLINICConnectionString {
            get {
                return ((string)(this["DERMA_CLINICConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HP\\SQLEXPRESS;Initial Catalog=DataClasses2;Integrated Security=True;E" +
            "ncrypt=True;TrustServerCertificate=True")]
        public string DataClasses2ConnectionString {
            get {
                return ((string)(this["DataClasses2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HP\\SQLEXPRESS;Initial Catalog=DERMA_CLINIC12;Integrated Security=True" +
            ";TrustServerCertificate=True")]
        public string DERMA_CLINIC12ConnectionString1 {
            get {
                return ((string)(this["DERMA_CLINIC12ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HP\\SQLEXPRESS;Initial Catalog=DERMA_CLINIC12;Integrated Security=True" +
            ";TrustServerCertificate=True")]
        public string DERMA_CLINIC12ConnectionString {
            get {
                return ((string)(this["DERMA_CLINIC12ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DONGTHUYUEH;Initial Catalog=DERMA_CLINIC;Integrated Security=True;Enc" +
            "rypt=False")]
        public string DERMA_CLINICConnectionString1 {
            get {
                return ((string)(this["DERMA_CLINICConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MINHMAIL;Initial Catalog=DataClasses2;Integrated Security=True;Encryp" +
            "t=True;TrustServerCertificate=True")]
        public string DataClasses2ConnectionString1 {
            get {
                return ((string)(this["DataClasses2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MSI;Initial Catalog=DERMA_CLINIC12;Integrated Security=True;Encrypt=T" +
            "rue;TrustServerCertificate=True")]
        public string DERMA_CLINIC12ConnectionString2 {
            get {
                return ((string)(this["DERMA_CLINIC12ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MSI\\MSSQLSERVER1;Initial Catalog=Clinic;Integrated Security=True;Encr" +
            "ypt=True;TrustServerCertificate=True")]
        public string ClinicConnectionString {
            get {
                return ((string)(this["ClinicConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MSI\\MSSQLSERVER1;Initial Catalog=DataClasses2;Integrated Security=Tru" +
            "e;Encrypt=True;TrustServerCertificate=True")]
        public string DataClasses2ConnectionString2 {
            get {
                return ((string)(this["DataClasses2ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DONGTHUYUEH;Initial Catalog=DataClasses2;Integrated Security=True;Enc" +
            "rypt=False")]
        public string DataClasses2ConnectionString3 {
            get {
                return ((string)(this["DataClasses2ConnectionString3"]));
            }
        }
    }
}
